## Text -> Vetors

# One Hot encoder
# Bag of words

In [5]:
import pandas as pd
messages=pd.read_csv('spamcollection/spam.csv',
                    sep='\t',names=["label","message"])

In [6]:
messages

,label,message
0,ham,Get 1GB data per day for Rs 199. Valid for 28 ...
1,ham,Unlimited calls and 2GB per day at Rs 299. Lim...
2,ham,Your plan expires tomorrow. Please recharge to...
3,ham,Recharge successful. Rs 249 plan activated. Va...
4,ham,Low balance alert. Your data pack is about to ...
5,spam,Congratulations! You have won a free iPhone. C...
6,ham,Special weekend offer: Extra 5GB data on recha...
7,ham,Reminder: Your daily data limit has been reached.
8,ham,Payment of Rs 199 received. Your pack is now a...
9,spam,Earn money from home easily. No investment req...


In [7]:
## Data Cleaning And Preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\YashasJ\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

## using PortStemmer

In [9]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [10]:
corpus = []
for i in range(0,len(messages)):
    review = re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review = review.lower()
    review = review.split()
    [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

corpus

['get gb data per day for rs valid for days recharge now',
 'unlimited calls and gb per day at rs limited time offer',
 'your plan expires tomorrow please recharge to continue services',
 'recharge successful rs plan activated valid for days',
 'low balance alert your data pack is about to expire',
 'congratulations you have won a free iphone click here to claim now',
 'special weekend offer extra gb data on recharge above rs',
 'reminder your daily data limit has been reached',
 'payment of rs received your pack is now active',
 'earn money from home easily no investment required join now',
 'recharge with rs and get gb per day plus ott subscription',
 'you have used percent of your data consider upgrading your plan',
 'your validity ends today recharge before midnight',
 'your recharge of rs is successful enjoy unlimited benefits',
 'get rich quick double your money in days click now',
 'night data unlimited from am to am with rs pack',
 'outgoing services will be stopped due to low 

### create bag of words

In [12]:
## Create the Bag OF Words model
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=100,binary=True)

In [14]:
X=cv.fit_transform(corpus).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(20, 100))

## using SnowballStemmer

In [ ]:
from nltk.stem import SnowballStemmer
snowball_stem = SnowballStemmer("english")

In [18]:
corpus = []
for i in range(0,len(messages)):
    review = re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review = review.lower()
    review = review.split()
    [snowball_stem.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

corpus

['get gb data per day for rs valid for days recharge now',
 'unlimited calls and gb per day at rs limited time offer',
 'your plan expires tomorrow please recharge to continue services',
 'recharge successful rs plan activated valid for days',
 'low balance alert your data pack is about to expire',
 'congratulations you have won a free iphone click here to claim now',
 'special weekend offer extra gb data on recharge above rs',
 'reminder your daily data limit has been reached',
 'payment of rs received your pack is now active',
 'earn money from home easily no investment required join now',
 'recharge with rs and get gb per day plus ott subscription',
 'you have used percent of your data consider upgrading your plan',
 'your validity ends today recharge before midnight',
 'your recharge of rs is successful enjoy unlimited benefits',
 'get rich quick double your money in days click now',
 'night data unlimited from am to am with rs pack',
 'outgoing services will be stopped due to low 

In [20]:
Y=cv.fit_transform(corpus).toarray()
Y


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(20, 100))

## Using Lemitization

In [23]:
from nltk.stem import WordNetLemmatizer
wordnetLem = WordNetLemmatizer()

In [24]:
corpus = []
for i in range(0,len(messages)):
    review = re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review = review.lower()
    review = review.split()
    [wordnetLem.lemmatize(word,pos='v') for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

corpus

['get gb data per day for rs valid for days recharge now',
 'unlimited calls and gb per day at rs limited time offer',
 'your plan expires tomorrow please recharge to continue services',
 'recharge successful rs plan activated valid for days',
 'low balance alert your data pack is about to expire',
 'congratulations you have won a free iphone click here to claim now',
 'special weekend offer extra gb data on recharge above rs',
 'reminder your daily data limit has been reached',
 'payment of rs received your pack is now active',
 'earn money from home easily no investment required join now',
 'recharge with rs and get gb per day plus ott subscription',
 'you have used percent of your data consider upgrading your plan',
 'your validity ends today recharge before midnight',
 'your recharge of rs is successful enjoy unlimited benefits',
 'get rich quick double your money in days click now',
 'night data unlimited from am to am with rs pack',
 'outgoing services will be stopped due to low 

In [25]:
Z=cv.fit_transform(corpus).toarray()
Z


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(20, 100))

## NGRAM

In [9]:
from nltk.corpus import stopwords
import re
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [10]:
import pandas as pd
messages=pd.read_csv('spamcollection/spam.csv',
                    sep='\t',names=["label","message"])

In [11]:
corpus = []
for i in range(0,len(messages)):
    review = re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review = review.lower()
    review = review.split()
    [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

corpus

['get gb data per day for rs valid for days recharge now',
 'unlimited calls and gb per day at rs limited time offer',
 'your plan expires tomorrow please recharge to continue services',
 'recharge successful rs plan activated valid for days',
 'low balance alert your data pack is about to expire',
 'congratulations you have won a free iphone click here to claim now',
 'special weekend offer extra gb data on recharge above rs',
 'reminder your daily data limit has been reached',
 'payment of rs received your pack is now active',
 'earn money from home easily no investment required join now',
 'recharge with rs and get gb per day plus ott subscription',
 'you have used percent of your data consider upgrading your plan',
 'your validity ends today recharge before midnight',
 'your recharge of rs is successful enjoy unlimited benefits',
 'get rich quick double your money in days click now',
 'night data unlimited from am to am with rs pack',
 'outgoing services will be stopped due to low 

In [34]:
## Create the Bag OF Words model with ngram 
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
# unigram garm
cv=CountVectorizer(max_features=1000,binary=True,ngram_range=(1,1))

In [35]:
X=cv.fit_transform(corpus).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(20, 110))

In [36]:
cv.vocabulary_

{'get': np.int64(44),
 'gb': np.int64(43),
 'data': np.int64(23),
 'per': np.int64(75),
 'day': np.int64(24),
 'for': np.int64(40),
 'rs': np.int64(87),
 'valid': np.int64(102),
 'days': np.int64(25),
 'recharge': np.int64(83),
 'now': np.int64(66),
 'unlimited': np.int64(99),
 'calls': np.int64(16),
 'and': np.int64(7),
 'at': np.int64(8),
 'limited': np.int64(57),
 'time': np.int64(95),
 'offer': np.int64(68),
 'your': np.int64(109),
 'plan': np.int64(77),
 'expires': np.int64(38),
 'tomorrow': np.int64(98),
 'please': np.int64(78),
 'to': np.int64(96),
 'continue': np.int64(21),
 'services': np.int64(89),
 'successful': np.int64(93),
 'activated': np.int64(2),
 'low': np.int64(58),
 'balance': np.int64(10),
 'alert': np.int64(4),
 'pack': np.int64(73),
 'is': np.int64(53),
 'about': np.int64(0),
 'expire': np.int64(37),
 'congratulations': np.int64(19),
 'you': np.int64(108),
 'have': np.int64(46),
 'won': np.int64(107),
 'free': np.int64(41),
 'iphone': np.int64(52),
 'click': np.i

In [37]:
# binary garm

cv=CountVectorizer(max_features=1000,binary=True,ngram_range=(1,2))
X=cv.fit_transform(corpus).toarray()
cv.vocabulary_

{'get': np.int64(100),
 'gb': np.int64(97),
 'data': np.int64(48),
 'per': np.int64(169),
 'day': np.int64(55),
 'for': np.int64(89),
 'rs': np.int64(200),
 'valid': np.int64(243),
 'days': np.int64(59),
 'recharge': np.int64(186),
 'now': np.int64(147),
 'get gb': np.int64(101),
 'gb data': np.int64(98),
 'data per': np.int64(53),
 'per day': np.int64(170),
 'day for': np.int64(57),
 'for rs': np.int64(91),
 'rs valid': np.int64(208),
 'valid for': np.int64(244),
 'for days': np.int64(90),
 'days recharge': np.int64(61),
 'recharge now': np.int64(189),
 'unlimited': np.int64(235),
 'calls': np.int64(33),
 'and': np.int64(15),
 'at': np.int64(18),
 'limited': np.int64(129),
 'time': np.int64(222),
 'offer': np.int64(154),
 'unlimited calls': np.int64(237),
 'calls and': np.int64(34),
 'and gb': np.int64(16),
 'gb per': np.int64(99),
 'day at': np.int64(56),
 'at rs': np.int64(19),
 'rs limited': np.int64(204),
 'limited time': np.int64(130),
 'time offer': np.int64(223),
 'your': np.in

In [38]:
# tri garm
cv=CountVectorizer(max_features=1000,binary=True,ngram_range=(3,3))
X=cv.fit_transform(corpus).toarray()
cv.vocabulary_

{'get gb data': np.int64(50),
 'gb data per': np.int64(48),
 'data per day': np.int64(22),
 'per day for': np.int64(89),
 'day for rs': np.int64(25),
 'for rs valid': np.int64(43),
 'rs valid for': np.int64(116),
 'valid for days': np.int64(133),
 'for days recharge': np.int64(42),
 'days recharge now': np.int64(28),
 'unlimited calls and': np.int64(129),
 'calls and gb': np.int64(13),
 'and gb per': np.int64(5),
 'gb per day': np.int64(49),
 'per day at': np.int64(88),
 'day at rs': np.int64(24),
 'at rs limited': np.int64(8),
 'rs limited time': np.int64(113),
 'limited time offer': np.int64(66),
 'your plan expires': np.int64(147),
 'plan expires tomorrow': np.int64(95),
 'expires tomorrow please': np.int64(40),
 'tomorrow please recharge': np.int64(128),
 'please recharge to': np.int64(96),
 'recharge to continue': np.int64(105),
 'to continue services': np.int64(125),
 'recharge successful rs': np.int64(104),
 'successful rs plan': np.int64(121),
 'rs plan activated': np.int64(114